package com.nfcreaderts;

public enum AndroidLibre_EVENTS {
    NFC_V_TAG_DETECECTED,
    NFC_CHECK_FAIL,
    NFC_ERROR_NO_TAG_DETECTED,
    NFC_ERROR_UNKNOWN,
    NFC_INITIALISATION_STARTED,
    NFC_INITIALISATION_DONE,
    NFC_INITIALISATION_FAILED,
    NFC_TAG_INSTANCE_CREATED,
    NFC_ERROR_IN_TRANSIEVE,
    NFC_READ_STARTED,
    NFC_READ_FINISHED,
    NFC_TAG_CONNECTED,
    NFC_TAG_CONNECTION_FAILED,
    ONE_BLOCK_READ,
    NFC_ERROR_CANNOT_READ_ANOTHER_READ_IN_PROGERSS,
    READING_STOPPED,
    READING_CANCELLED,
}
